- hosts: all
  collections:
    - ansible.controller
  tasks:
    - tower_job_list:
        status: successful
        tower_host: localhost
        tower_username: admin
        tower_password: redhat
        validate_certs: no   
